import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";

import "./globals.css";
import BackgroundVisualLayers from "@/components/background-visual-layers";
import Header from "@/components/header";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BackgroundVisualLayers />
        <SkipToContent />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

function SkipToContent() {
  return (
    <Link
      href="#content"
      className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:bg-[#0D0F14] focus:text-[#E5E7EB] focus:border focus:border-[#22D3EE] focus:px-3 focus:py-2 focus:rounded"
    >
      Skip to content
    </Link>
  );
}
